// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLMuJsMYQekDZjnXAkoEdrufD0v-aV22Q',
    appId: '1:769398584437:web:222b730efe1059ad98b43c',
    messagingSenderId: '769398584437',
    projectId: 'moon-firebase-flutter-01',
    authDomain: 'moon-firebase-flutter-01.firebaseapp.com',
    storageBucket: 'moon-firebase-flutter-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UaoyFNZ_gOmav6XgG4lsiipWtwqnK4A',
    appId: '1:769398584437:android:224bba2ca55f4da498b43c',
    messagingSenderId: '769398584437',
    projectId: 'moon-firebase-flutter-01',
    storageBucket: 'moon-firebase-flutter-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTXMmYoLLEqnQdAEklNIrJ51hyle43RM',
    appId: '1:769398584437:ios:b188b090b9c0d38598b43c',
    messagingSenderId: '769398584437',
    projectId: 'moon-firebase-flutter-01',
    storageBucket: 'moon-firebase-flutter-01.appspot.com',
    androidClientId: '769398584437-0sonuvuc4n1bs30rgb3ncaq2r91pdqla.apps.googleusercontent.com',
    iosClientId: '769398584437-8rer2df1i5po73dqr3vap3s8r7o0rb3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthMapp',
  );
}
