// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNSFhxjqFLlDRoWUnF0zw2pZ7EAYLL-Qk',
    appId: '1:940916149285:web:2e1e8948eb2281369fc3cc',
    messagingSenderId: '940916149285',
    projectId: 'moon-firebase-flutter-prj',
    authDomain: 'moon-firebase-flutter-prj.firebaseapp.com',
    storageBucket: 'moon-firebase-flutter-prj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaX5GUNVtVMEtKjDbDZui0IAqKoYEOI9o',
    appId: '1:940916149285:android:dc0d4cb42916ce849fc3cc',
    messagingSenderId: '940916149285',
    projectId: 'moon-firebase-flutter-prj',
    storageBucket: 'moon-firebase-flutter-prj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7qk-yP8O9aCA3wd1wlDgW-UcaWrqaRU',
    appId: '1:940916149285:ios:b1f2779c2cc258e99fc3cc',
    messagingSenderId: '940916149285',
    projectId: 'moon-firebase-flutter-prj',
    storageBucket: 'moon-firebase-flutter-prj.appspot.com',
    iosClientId: '940916149285-61peoctn6namvs7gt8gdaf2qeehc3ifv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreQuickstart',
  );
}
